global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'microflex-backend'
    static_configs:
      - targets: ['backend-service:5000']

  - job_name: 'microflex-frontend'
    static_configs:
      - targets: ['frontend-service:8080']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - 'alertmanager:9093'

rule_files:
  - "alert_rules.yml"
